### ISSUE TITLE
use a templating mechanism for new ontology &c

### ISSUE THREAD

**Issue by johanwk** [johanwk/elot#4]
UPDATE. Try to go for `tempo` templates. One good reason is, they are built in.

The Yasnippet package is suitable. The [Yankpad](https://github.com/Kungsgeten/yankpad) package makes it easier to use with org, and is perhaps preferable for this project.

It should be easy to request "new blank ontology" and be prompted for, e.g., ontology URI, then obtain a new org-mode document to write the ontology.

Similarly, provide snippets for defining OWL class/property with common annotation properties already added to be filled out. Also, for diagrams with rdfpuml.

**Comment by VladimirAlexiev** [comment]
Agree, templates are very useful! Need to see some examples to figure out useful templates. 

I personally use the much simpler `org-structure-template-alist` mechanism.
It expands eg `<t` at the start of line to:
```
#+begin_src turtle

#+end_src
```

Here's my setup:
```elisp
(setq org-structure-template-alist
      ;; (org-tempo-add-templates)
      '(
        ;; ("I" . "include") ; standard
        ;; standard in org-tempo-keywords-alist:
        ;; ("L" . "latex")
        ;; ("H" . "html")
        ;; ("A" . "ascii")
        ;; ("i" . "index")

        ("ee" . "export")
        ("ea" . "export ascii")
        ("eh" . "export html")
        ("el" . "export latex")

        ("s" . "src")
        ("4" . "src m4")
        ("d" . "src dot :file ./img/TODO.png")
        ("g" . "src graphql")
        ("j" . "src json")
        ("p" . "src perl")
        ("S" . "src sparql")
        ("t" . "src turtle")
        ("u" . "src plantuml :file ./img/TODO.png")
        ("x" . "src shexc")
        ("y" . "src yaml")

        ("a" . "abstract")
        ("c" . "center")
        ("C" . "comment")
        ("e" . "example")
        ("n" . "notes")
        ("q" . "quote")
        ("V" . "verbatim")
        ("v" . "verse")
        ))
```
It uses `tempo` templates, eg the plantuml template above generates a function like `tempo-template-org-src-plantuml-:file-./img/TODO.png`

**Comment by johanwk** [comment]
A note. To locate the snippets needed, look at [https://github.com/AndreaCrotti/yasnippet-snippets/blob/master/yasnippet-snippets.el and ](https://github.com/AndreaCrotti/yasnippet-snippets/blob/e6ec9f1822913cea7dc67cde6aeb8f2625980950/yasnippet-snippets.el#L35)

**Comment by johanwk** [comment]
Added two important templates in a74af84. They query the user for values. 

These should be used in a blank org-mode file.
 - `<oh` inserts document header
 - `<os` inserts skeleton declaring prefixes, and the ontology, and inserts headings for classes and relations
