### ISSUE TITLE
Use semantic newlines

### ISSUE THREAD

**Issue by VladimirAlexiev** [johanwk/elot#42]
Newlines in markdown/org don't matter for the final rendered product, but they matter a lot for collaborators and source control.
See https://sembr.org/.

This is bad:

>  2. The [[https://plantuml.com/][PlantUML]] tool is needed for diagrams. Download
    the latest version from [[https://plantuml.com/download][PlantUML Downloads]] (tested with [[https://github.com/plantuml/plantuml/releases/download/v1.2024.3/plantuml-1.2024.3.jar][plantuml-1.2024.3.jar]]) to your =bin=
    folder. For convenience, rename it as just =plantuml.jar= (on Linux,
    make a symlink).

This is much better:
>  2. The [[https://plantuml.com/][PlantUML]] tool is needed for diagrams. 
    Download the latest version from [[https://plantuml.com/download][PlantUML Downloads]] 
    (tested with [[https://github.com/plantuml/plantuml/releases/download/v1.2024.3/plantuml-1.2024.3.jar][plantuml-1.2024.3.jar]]) 
    to your =bin= folder. 
    For convenience, rename it as just =plantuml.jar= (on Linux, make a symlink).

Keep each "sub-thought" on a separate line. Don't be afraid to use a bit longer lines. Don't use Emacs "fill-paragraph".

You don't need to edit all doc files now. But:
- Do it for future writeups
- I'll make such changes as I suggest minor patches.

**Comment by johanwk** [comment]
This is great advice, thanks! I'll keep this in mind from now on, and also share with friends and colleagues :)
