### ISSUE TITLE
pass prefixes to org-babel-sparql--current-curies

### ISSUE THREAD

**Issue by VladimirAlexiev** [johanwk/elot#47]
Sorry, I meant to make this issue in another repo: https://github.com/ljos/sparql-mode/issues/76.
Posted question to Github why can't I transfer the issue: https://github.com/orgs/community/discussions/118502

**Comment by johanwk** [comment]
Hook added so the prefixes in `org-link-abbrev-alist-local` are now updated from the org table `prefix-table` on save  9665a6f
