### ISSUE TITLE
literary -> literate

### ISSUE THREAD

**Issue by VladimirAlexiev** [johanwk/elot#49]
- change the repo description from "Emacs Literary Ontology Tool" to "Emacs Literate Ontology Tool"
- add 1 paragraph at start of readme

> [Literate programming](https://en.wikipedia.org/wiki/Literate_programming) is a paradigm where the creator of some technical artefact focuses on the explanation and readability of each technical construct, rather than its formal machine-readable definition.
The machine-readable artefacts are then extracted through a process called "tangling".
ELOT takes inspiration from this paradigm and uses the excellent Emacs Orgmode plain-text format to create an author- and reader-friendly ontology authoring environment.
Ontological constructs are generated from narrative sections and Manchester Notation (OMN) fragments. Diagrams are generated from Turtle examples or SPARQL queries by using the `rdfpuml` tool.
The tool then extracts ontological definitions (OMN or Turtle) and documentation (HTML or PDF).

**Comment by johanwk** [comment]
Good catch with the description! This obviously isn't for writing fine literature.

Please feel free to add to or change the README when you see the need. The text is very helpful.

**Comment by VladimirAlexiev** [comment]
Hey @mhodki , want to make your first pull request (PR)?
- Clone this repo to github.com/mhodki
- add the above text to the README
- Push to your repo, then Github will suggest you create a PR

**Comment by johanwk** [comment]
Closed in 327ccbe. Great improvement to have these paragraphs in the introduction!
