### ISSUE TITLE
Cannot install package in Doom Emacs due to unexpected values in Package-Requires

### ISSUE THREAD

**Issue by weavermarquez** [johanwk/elot#53]
Submitting a pull request to fix this. Issue for documentation.

### Error Description
When attempting to install this package on Doom Emacs, running `doom sync` expects that `Package-Requires` is an elisp list. The extra text in there results in a compilation error by attempting to install `\...`

https://github.com/johanwk/elot/blob/f6a64c5362becb32001af1193503119e9e0934e8/elot-package/elot.el#L8

Compare to org-ql, which compiles as expected:

    ;; Package-Requires: ((emacs "27.1") (compat "29.1") (dash "2.18.1") (f "0.17.2") (map "2.1") (org "9.0") (org-super-agenda "1.2") (ov "1.0.6") (peg "1.0.1") (s "1.12.0") (transient "0.1") (ts "0.2-pre"))

#### System Details

Emacs 29.3
Doom v3.0.0-pre

#### Thrown error:
``` elisp
((error "Could not find package %S. Updating recipe repositories: %S with `straight-pull-recipe-repositories' may fix this" \...
	(org-elpa melpa nongnu-elpa gnu-elpa-mirror el-get emacsmirror-mirror))
 ((debugger-may-continue . t)
  (inhibit-redisplay)
  (inhibit-debugger . t)
  (inhibit-changing-match-data)))

```

#### Doom Emacs Recipe
``` elisp 
;(package! htmlize) ; already in doom emacs
(package! omn-mode)
(package! sparql-mode)
(package! plantuml-mode)
(package! hydra)
(package! org-ql)

(package! elot
   :recipe (:host github :repo "johanwk/elot" :files("elot-package/*")))
```

### Workaround

Until this value is fixed, a workaround is simple:
1. Clone the repo into your Doom config e.g. `~/.config/doom`,
2. Edit the `Package-Requires` line
3. Adjust the recipe to use a local repo.

In `elot-package/elot.el`

    ;; Package-Requires: ((emacs "29.2"))

Adjusted Recipe:
``` elisp
(package! elot
  :recipe (:local-repo "elot" :files("elot-package/*")))
```

**Comment by weavermarquez** [comment]
In my pull request I simply reduced it to

    ;; Package-Requires: ((emacs "29.2"))

Idk how Package-Require really works, but here's the requirements for your convenience based on my current Doom install:

    ;; Package-Requires: ((emacs "29.2") (htmlize "1.57") (omn-mode "1.3") (sparql-mode "4.0.3") (plantuml-mode "1.2.9") (hydra "0.15.0") (org-ql "0.8.5"))

**Comment by johanwk** [comment]
Hi sorry for taking ridiculously long to respond. The project is not abandoned, just in case you were wondering. I appreciate the input. I don't yet know how to make a proper ELOT package, but your input should help some users, so I'll make the change as you suggest.

It would be really interesting to hear whether you have found the package useful for some ontology work!
