### ISSUE TITLE
Manchester Syntax support

### ISSUE THREAD

**Issue by VladimirAlexiev** [johanwk/elot#8]
Do we want a setup for Manchester Syntax? At least syntax highlighting, maybe also indentation.
My org code blocks are highlighted, I think thanks to a module by the fabulous "jkitchin".

There is `omn-mode` for emacs:
- http://homepages.cs.ncl.ac.uk/phillip.lord/emacs.html 
- https://www.russet.org.uk/blog/2161/
- https://www.russet.org.uk/blog/2200/
- https://douroucouli.wordpress.com/2014/03/30/the-perils-of-managing-owl-in-a-version-control-system/:  discussion

It is in ELPA:
- https://elpa.gnu.org/packages/omn-mode.html
- https://github.com/emacsmirror/omn-mode (https://github.com/phillord/phil-emacs-packages/blob/master/omn-mode.el is older)

BTW, it's used in a Clojure-based ontology creation environment, similar to the idea of your "elot":
https://github.com/phillord/tawny-owl

**Comment by johanwk** [comment]
I use `omn-mode` myself. It works, but could be improved -- especially when exporting to HTML, prefixes are not handled well. Probably omn-mode is such a "must have" for ELOT that it would make sense to make it a dependency, in some sense of the word. It seems natural to me to automatically install it with ELOT, which I think you are suggesting.

There's an interesting new development for Manchester Syntax described here: https://ceur-ws.org/Vol-3515/paper-12.pdf, which is also apparently not in the OWL API https://github.com/owlcs/owlapi/pull/1104. I would think the omn-mode doesn't cover the latest improvements. Well, maybe we could try to help with that.

**Comment by VladimirAlexiev** [comment]
- when we make a module header (#9), we'll include dependency on `omn-mode`, similar to this:
```
;; Package-Requires: ((emacs "26.1") (dash "2.12") (s "1.10.0") (org "9.3") (compat "29.1"))
```
- we should also add 
```elisp
(require `omn-mode)
```
- can you elaborate on "prefixes are not handled well? Do you mean the coloring is wrong?
- I've browsed the first page of the paper "Extending OWL2 Manchester Syntax to Include Missing Features from OWL2 Abstract Syntax" and it doesn't seem to introduce new keywords, so no change will be needed to omn-mode.
- If new changes (or other fixes) are needed, sure we can adopt omn-mode.

**Comment by johanwk** [comment]
omn-mode added as a requirement
